FROM payara/server-full:5.2021.10

# Copy JDBC driver
COPY mssql-jdbc-11.2.0.jre8.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
#COPY .../target/tcmapp.war /opt/payara/deployments/tcmapp.war
#COPY ./../target/tcmapp.war /opt/payara/deployments/tcmapp.war


